version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - mynetwork

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork: